version: '3'
services:
    php:
        build:
            context: ./
            dockerfile: ./php.Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - './:/var/www/html'
            - './php.ini:/usr/local/etc/php/php.ini'
            - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
        networks:
            - internal

    nginx:
        image: nginx:stable
        ports:
            - 8080:80
        volumes:
            - './:/var/www/html'
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - internal

    db:
        image: postgres:15.1-alpine
        container_name: db_postgres
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - /home/alex/PhpstormProjects/startup-it/database_project:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: database
        networks:
            - internal
    adminer:
        image: adminer
        restart: always
        ports:
            - "8081:8080"
        networks:
            - internal

networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.220.0/28
